"""initial schema

Revision ID: 8404f3cb8c30
Revises: 
Create Date: 2026-08-23 09:14:18.120729
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8404f3cb8c30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('safe_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('investigation_sessions',
    sa.Column('session_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RECORDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'ARCHIVED', name='session_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expected_speaker_count', sa.Integer(), server_default='2', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_sessions_created_by'), 'investigation_sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_session_date'), 'investigation_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_session_number'), 'investigation_sessions', ['session_number'], unique=True)
    op.create_index(op.f('ix_investigation_sessions_status'), 'investigation_sessions', ['status'], unique=False)
    op.create_table('investigator_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('military_id', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('military_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles')
    )
    op.create_table('workstations',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('stt_provider', sa.String(length=100), nullable=True),
    sa.Column('stt_model', sa.String(length=200), nullable=True),
    sa.Column('stt_model_revision', sa.String(length=100), nullable=True),
    sa.Column('diarization_provider', sa.String(length=100), nullable=True),
    sa.Column('diarization_model', sa.String(length=200), nullable=True),
    sa.Column('diarization_model_revision', sa.String(length=100), nullable=True),
    sa.Column('processing_device', sa.String(length=50), nullable=True),
    sa.Column('gpu_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'DEGRADED', 'OFFLINE', name='workstation_status'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workstations_agent_id'), 'workstations', ['agent_id'], unique=True)
    op.create_table('audio_recordings',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('BROWSER_RECORDING', 'FILE_UPLOAD', name='recording_source'), nullable=False),
    sa.Column('upload_status', sa.Enum('PENDING', 'UPLOADED', 'DISABLED', name='recording_upload_status'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['investigation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_recordings_session_id'), 'audio_recordings', ['session_id'], unique=False)
    op.create_index(op.f('ix_audio_recordings_sha256'), 'audio_recordings', ['sha256'], unique=False)
    op.create_table('session_investigators',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('investigator_id', sa.UUID(), nullable=False),
    sa.Column('assignment_role', sa.Enum('LEAD', 'ASSISTANT', name='assignment_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['investigator_id'], ['investigator_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['investigation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'investigator_id', name='uq_session_investigator')
    )
    op.create_index(op.f('ix_session_investigators_investigator_id'), 'session_investigators', ['investigator_id'], unique=False)
    op.create_index(op.f('ix_session_investigators_session_id'), 'session_investigators', ['session_id'], unique=False)
    op.create_table('session_speakers',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('speaker_label', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('speaker_role', sa.Enum('INVESTIGATOR', 'SUBJECT', 'WITNESS', 'OTHER', 'UNKNOWN', name='speaker_role'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['investigation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'speaker_label', name='uq_session_speaker_label')
    )
    op.create_index(op.f('ix_session_speakers_session_id'), 'session_speakers', ['session_id'], unique=False)
    op.create_table('subjects',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('military_id', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['investigation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_session_id'), 'subjects', ['session_id'], unique=False)
    op.create_table('local_processing_jobs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('workstation_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('agent_state', sa.String(length=40), nullable=True),
    sa.Column('token_nonce', sa.String(length=64), nullable=False),
    sa.Column('token_issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_accept_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('failure_stage', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('agent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['audio_recordings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['investigation_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_nonce')
    )
    op.create_index(op.f('ix_local_processing_jobs_idempotency_key'), 'local_processing_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_local_processing_jobs_session_id'), 'local_processing_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_local_processing_jobs_status'), 'local_processing_jobs', ['status'], unique=False)
    op.create_table('transcripts',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'REVIEWED', name='transcript_status'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('stt_provider', sa.String(length=100), nullable=True),
    sa.Column('stt_model', sa.String(length=200), nullable=True),
    sa.Column('stt_model_revision', sa.String(length=100), nullable=True),
    sa.Column('diarization_provider', sa.String(length=100), nullable=True),
    sa.Column('diarization_model', sa.String(length=200), nullable=True),
    sa.Column('diarization_model_revision', sa.String(length=100), nullable=True),
    sa.Column('vad_model', sa.String(length=200), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('processing_device', sa.String(length=50), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['local_processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['audio_recordings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['investigation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_transcripts_session_id'), 'transcripts', ['session_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=32), nullable=False),
    sa.Column('start_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('end_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_overlap', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'sequence', name='uq_segment_sequence')
    )
    op.create_index(op.f('ix_transcript_segments_speaker_label'), 'transcript_segments', ['speaker_label'], unique=False)
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_speaker_label'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_transcripts_session_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_local_processing_jobs_status'), table_name='local_processing_jobs')
    op.drop_index(op.f('ix_local_processing_jobs_session_id'), table_name='local_processing_jobs')
    op.drop_index(op.f('ix_local_processing_jobs_idempotency_key'), table_name='local_processing_jobs')
    op.drop_table('local_processing_jobs')
    op.drop_index(op.f('ix_subjects_session_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_session_speakers_session_id'), table_name='session_speakers')
    op.drop_table('session_speakers')
    op.drop_index(op.f('ix_session_investigators_session_id'), table_name='session_investigators')
    op.drop_index(op.f('ix_session_investigators_investigator_id'), table_name='session_investigators')
    op.drop_table('session_investigators')
    op.drop_index(op.f('ix_audio_recordings_sha256'), table_name='audio_recordings')
    op.drop_index(op.f('ix_audio_recordings_session_id'), table_name='audio_recordings')
    op.drop_table('audio_recordings')
    op.drop_index(op.f('ix_workstations_agent_id'), table_name='workstations')
    op.drop_table('workstations')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('investigator_profiles')
    op.drop_index(op.f('ix_investigation_sessions_status'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_session_number'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_session_date'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_created_by'), table_name='investigation_sessions')
    op.drop_table('investigation_sessions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    for enum_name in (
        'transcript_status', 'job_status', 'speaker_role', 'assignment_role',
        'recording_upload_status', 'recording_source', 'workstation_status', 'session_status',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
