"""voice enrollments and identity suggestions

Revision ID: f7fcea0351f9
Revises: d82371d11435
Create Date: 2026-08-24 09:58:41.738809
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f7fcea0351f9'
down_revision = 'd82371d11435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column does not create the PostgreSQL enum type (unlike create_table): do it first.
    identification_status = postgresql.ENUM(
        'NONE', 'SUGGESTED', 'CONFIRMED', 'REJECTED', name='identification_status'
    )
    identification_status.create(op.get_bind(), checkfirst=True)
    op.create_table('voice_enrollments',
    sa.Column('person_name', sa.String(length=200), nullable=False),
    sa.Column('person_reference', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('model_revision', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('sample_seconds', sa.Float(), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('source_speaker_label', sa.String(length=32), nullable=True),
    sa.Column('consent_recorded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enrolled_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrolled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['investigation_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_reference', 'model', name='uq_voice_enrollment_person_model')
    )
    op.create_index(op.f('ix_voice_enrollments_person_reference'), 'voice_enrollments', ['person_reference'], unique=False)
    op.add_column('session_speakers', sa.Column('identification_status', postgresql.ENUM('NONE', 'SUGGESTED', 'CONFIRMED', 'REJECTED', name='identification_status', create_type=False), server_default='NONE', nullable=False))
    op.add_column('session_speakers', sa.Column('suggested_name', sa.String(length=200), nullable=True))
    op.add_column('session_speakers', sa.Column('suggested_enrollment_id', sa.UUID(), nullable=True))
    op.add_column('session_speakers', sa.Column('suggested_score', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('session_speakers', sa.Column('suggested_model', sa.String(length=200), nullable=True))
    op.add_column('session_speakers', sa.Column('suggested_model_revision', sa.String(length=100), nullable=True))
    op.add_column('session_speakers', sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('session_speakers', sa.Column('decided_by', sa.UUID(), nullable=True))
    op.add_column('session_speakers', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('session_speakers', sa.Column('voice_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key('fk_session_speakers_decided_by', 'session_speakers', 'users', ['decided_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_session_speakers_suggested_enrollment', 'session_speakers', 'voice_enrollments', ['suggested_enrollment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # dropping the columns below also drops their foreign keys in PostgreSQL
    op.drop_column('session_speakers', 'voice_embedding')
    op.drop_column('session_speakers', 'decided_at')
    op.drop_column('session_speakers', 'decided_by')
    op.drop_column('session_speakers', 'suggested_at')
    op.drop_column('session_speakers', 'suggested_model_revision')
    op.drop_column('session_speakers', 'suggested_model')
    op.drop_column('session_speakers', 'suggested_score')
    op.drop_column('session_speakers', 'suggested_enrollment_id')
    op.drop_column('session_speakers', 'suggested_name')
    op.drop_column('session_speakers', 'identification_status')
    op.drop_index(op.f('ix_voice_enrollments_person_reference'), table_name='voice_enrollments')
    op.drop_table('voice_enrollments')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS identification_status')
