import { strict as assert } from 'node:assert';
import { groupSpeakerObservations, transcriptSpeakerOptions } from '../src/lib/transcript-speakers';
import type { Speaker, Segment } from '../src/api/types';
const speaker = (label: string, identity: string | null, name: string) => ({ speaker_label:label, identity_id:identity, display_name:name }) as Speaker;
const segment = (label: string) => ({speaker_label:label}) as Segment;
const speakers = [speaker('A','one','علي'),speaker('B','one','علي'),speaker('C','two','علي'),speaker('D',null,'مجهول'),speaker('E',null,'مجهول'),speaker('old','old','قديم')];
const options = transcriptSpeakerOptions(speakers, ['A','B','C','D','E'].map(segment));
assert.equal(options.length,4);
assert.deepEqual(options.find(o => o.key === 'person:one')?.labels,['A','B']);
assert.equal(options.some(o => o.key === 'person:old'),false);
assert.equal(new Set(options.map(o => o.name)).size,4);
assert.equal(transcriptSpeakerOptions(speakers,[]).length,0);
const observations = speakers.map((s, i) => ({ ...s, id: String(i), segment_count: i + 1, total_seconds: 10 }));
const people = groupSpeakerObservations(observations);
assert.equal(people.length, 5);
assert.equal(people.find(p => p.key === 'person:one')?.observations.length, 2);
assert.equal(people.find(p => p.key === 'person:one')?.segmentCount, 3);
assert.equal(people.find(p => p.key === 'person:one')?.totalSeconds, 20);
assert.equal(people.filter(p => !p.identified).length, 2);
assert.equal(people.filter(p => p.name === 'علي').length, 2);
assert.equal(groupSpeakerObservations([]).length, 0);
console.log('Transcript filter: identity grouping, recording scope and name disambiguation passed.');
