from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[1]
def edit(path, fn):
    p = ROOT / path
    p.write_text(fn(p.read_text(encoding='utf-8')), encoding='utf-8')

edit('central/backend/app/schemas/investigations.py', lambda s: re.sub(r'        """A military subject.*?        """', '        """A supplied service number needs its force to be useful identity evidence."""', s, count=1, flags=re.S).replace('        # happens whether or not the person can be identified, and they honestly get no\n        # reference. Refusing that would make the system unusable exactly when it matters.', '        # happens even when their service details have not been established.').replace('    # The reference is what lets a speaker be bound to this person, and through that a voice\n    # print. It is null until they are assigned to a session, which is when they are registered.', '    # Assignment registers the investigator as a person with a stable UUID.'))
edit('central/backend/app/api/investigations.py', lambda s: re.sub(r'        # A profile predating the requirement.*?        try:', '        # A legacy profile without a name remains visible but cannot identify a speaker.\n        try:', s, count=1, flags=re.S).replace('A row with no reference is still returned', 'A row with no identity is still returned'))
edit('central/backend/app/api/voice.py', lambda s: re.sub(r'    # Enrolment neither creates nor establishes.*?    if speaker.identity_id', '    # Enrollment requires a previously selected person; it never infers or creates one.\n    if speaker.identity_id', s, count=1, flags=re.S).replace('    # The registry is the sole authority for both snapshot values. body.person_name and\n    # body.person_reference are no longer consulted, and display_name never was eligible:', '    # The registry owns the enrollment name snapshot; client names are not consulted:'))
edit('central/backend/app/schemas/voice.py', lambda s: re.sub(r'    """Create a voice template.*?    """', '    """Enroll an identified speaker. The server resolves their person UUID and name."""', s, count=1, flags=re.S))
edit('central/frontend/src/components/voice/IdentifySpeakerDialog.tsx', lambda s: re.sub(r'^/\*.*?\*/', '/** Select an existing person by UUID or register a new participant, then link the speaker. */', s, count=1, flags=re.S).replace('selection is still by reference, never name', 'selection is by UUID, never name').replace('        // mode "new" carries the whole form: its identifiers are what the backend derives or\n        // issues the reference from.', '        // New people carry their structured details and documents.').replace('identity_name and reference_number', 'identity_name and identity_id'))
edit('central/frontend/src/components/transcript/SpeakerPicker.tsx', lambda s: re.sub(r'^/\*.*?\*/', '/** Select a session participant or registry person using their stable UUID. */', s, count=1, flags=re.S).replace('Matching is by canonical reference', 'Matching is by person UUID').replace('merged reference', 'merged UUID'))
edit('central/frontend/src/components/subjects/SubjectFields.tsx', lambda s: re.sub(r'            \{/\* الجهاز and الرقم العسكري.*?\*/\}', '            {/* Service numbers are unique only within their security branch. */}', s, count=1, flags=re.S))

notice = '> **Updated identity model:** Person reference numbers have been removed. People now use internal UUIDs. See [the current identity contract and migration](person-identity-migration.md). Reference-number descriptions below document the earlier implementation.\n\n'
for path in ['docs/subject-identity.md','docs/voice-enrollment-guide.md','docs/central-server.md','docs/database-relationships.md','docs/speaker-identification.md']:
    edit(path, lambda s: s.split('\n',1)[0]+'\n\n'+notice+s.split('\n',1)[1].lstrip('\n'))
edit('docs/README.md', lambda s: re.sub(r'^\| \*\*الرقم المرجعي\*\*.*$', '| **هوية الشخص** | Internal UUID linking a person across sessions and voiceprints; selected through the person picker, never typed. See [migration notes](person-identity-migration.md). |', s, flags=re.M))
edit('docs/troubleshooting.md', lambda s: re.sub(r'^\| \*\*الرقم المرجعي\*\*.*\n', '| **الرقم المرجعي** is absent | the reference system has been retired | select the person by name; internal UUIDs preserve links. Reload older clients after deployment. |\n', s, flags=re.M))
